### ISSUE TITLE
Always register my app in OSM

### ISSUE THREAD

**Issue by GuillaumeAmat** [jaredhanson/passport-openstreetmap#2]
When I integrated passport-openstreetmap, I thought:
- The user clicks on the login/register button
- Thanks to passport-osm, he is redirected to osm.org
- He accepts to register my app in OSM
- He is redirected back to my app
- He logs out
- He come back and click again on the login button
- He's logged, without being redirected to osm.org

But it's not what it is happening right now. Instead, the user is always redirected to osm.org, asked to grant my app in OSM again and again. And my app appears a lot of time in the OAuth registered apps in osm.org.

Is it the expected behavior? Am I missing something? Thanks!

**Comment by TheFive** [comment]
Expected: No.
Missing: A lot. All information about your code, so help is hard. :-)

a) How do you store your session. ?
If you want a deep dive in you can look in your browser for your session cookie and in your session store wether the session is stored or not. If you do not use a session store you have to login every time.
b) The information in openstreetmap documents every oauth token you have requesting. As the request is done every time, you have a lot of tokens in your OSM Profile, thats correct.
c) To make the session work, have a look that all domains are correct in spelling, this includes HTTP versus HTTPS, that makes a different too
d) There are users, that delete their session cookies every time, they close their browser. Than you have to log in again in OpenStreetMap and you obtain a new token.

If you do not find the issue with this small hints, please post version of passport, passport-openstreetmap, (i had trouble in using passport <0.3.x), and post your relevant code here.

Thanks Christoph

**Comment by GuillaumeAmat** [comment]
@TheFive Thanks for your answer. You confirm that the current behavior is « normal » in the way I can't improve it for now.
