### ISSUE TITLE
introduction of https redirect in openstreetmap.

### ISSUE THREAD

**Issue by TheFive** [jaredhanson/passport-openstreetmap#6]
https://twitter.com/osm_tech/status/950778842402222082

"We are prepping HTTPS-by-default for the main #OpenStreetMap If you have developed an oAuth client, please test it ASAP against the preview site: master.apis.dev.openstreetmap.org report back to irc.osm.org #osm-dev"

Tested on 9.1.2017 against master api. for now it looks, that the path in the module has to be exchanged to https instead of http. 

Try to get some information from osm development team.

**Comment by TheFive** [comment]
What happens:
if you do not change the module from http://openstreetmap.org to https://openstreetmap.org you are always redirected to the grant access page of openstreetmap.

is it possible, that some information (e.g. access tokens) are not send again after a redirect ?

**Comment by karthicks** [comment]
I'm running into a slightly different issue:

```
https://.../auth/openstreetmap/callback?oauth_token=2rVuKIPa9Ucj6iHPlh2bRWLAk50URC693IwklW65

Error: failed to find request token in session
    at Strategy.OAuthStrategy.authenticate (.../node_modules/passport-openstreetmap/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js:124:54)
    at attempt (.../node_modules/passport/lib/middleware/authenticate.js:348:16)


```

Looks like the callback is missing the `oauth_verifier` parameter, but I'm not sure if that's the root cause: https://wiki.openstreetmap.org/wiki/OAuth.

-Karthick

**Comment by nickw1** [comment]
I am also getting the 'failed to find request token in session' in my OSM client application. Oddly I myself can complete the process without problems, but other users can't.

Changing the OSM URLs to HTTPS did not help. 

The missing `oauth_verifier` could well be the problem, as I think that's required, though the inconsistency is odd.

**Comment by TheFive** [comment]
I am using express with passport now for several years, and did not have this problem.

Can you reduce your code to a minimum, so that you can publish it here. I suggest to create a new issue, as it is not really in the redidirect https topic, and the request would be more helpful for other users with a better topic name.

I will close this topic.

For all, who have trouble with this redirect, you can simple change the url while creating the strategy.
e.g. see: https://github.com/TheFive/osmbc/blob/master/routes/auth.js#L83
